#pip3 install -r requirements.txt

from docx import Document
from docx.shared import Inches
# import pyttsx3

# pyttsx3.speak('Hello')

document=Document()

document.add_picture('piggy.png',width=Inches(2.0))

name=input('what is your name')
phone=input('what is your phone number')

document.add_paragraph(name+'|'+phone)

document.add_heading('About me')
me=input('Tell me about yourself')
document.add_paragraph(me)

document.add_heading('Working Experience')

def Expe():
    company=input('Your company')
    Date=input('From date')
    To=input('To date')
    experience=input('Describe the Experience')

    p=document.add_paragraph()
    p.add_run(company+'').bold=True
    p.add_run(Date+'-'+To+'\n').italic=True
    p.add_run(experience)

Expe()

while True:
    More_exp=input('More experience,Yes or No  ')
    if More_exp.lower() =='yes':
        Expe()
    else:
        break

document.add_heading('Skills')

def skil():
    skill=input('Skills')
    p=document.add_paragraph(skill)
    p.style='List Bullet'

skil()

while True:
    More_skill=input('More skill,yes or no ')
    if More_skill.lower() == 'yes':
        skil()
    else:
        break

section=document.sections[0]
footer=section.footer
p=footer.paragraphs[0]
p.text="It's generated by Python"

document.save('cv.docx')